<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Gathering</title>
    <link rel="stylesheet" href="static/css/app.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>

<body class="bg">
<div style="height: 70px;"></div>
<div class="container">
    <div class="box-home padding-medium">
        <div class="flex center-horizontal text-size-very-small" style="text-align: justify">
            <div class="margin-large">
                <?php echo $content;?>
            </div>
        </div>
        <form method="post" class="flex center-horizontal margin-bot-medium" action="/forms">
            <input type="hidden" name="state" value="5">
            <input type="submit" value="Lanjut" class="btn btn-outline-dark one-third">
        </form>
    </div>
</div>
<div style="height: 40px;"></div>
</body>
</html>