<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Gathering</title>
    <link rel="stylesheet" href="static/css/app.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>

<body class="bg">
<div style="height: 70px;"></div>
<div class="container">
    <div class="box-home padding-medium">
        <form method="post" action="/forms">
            <div class="margin-large">
                <input type="hidden" name="state" value="8">
                <div>
                    <p>Apakah berita yang dipublikasikan diralat sehari setelah dipublikasi?</p>
                    <label><input type="radio" required value="1" name="dbrief_1">Ya</label>
                    <label class="margin-left-medium"><input type="radio" value="0" name="dbrief_1">Tidak</label>
                </div>
                <br>
                <div>
                    <p>Apakah Anda membaca ralat terhadap artikel tersebut?</p>
                    <label><input type="radio" required value="1" name="dbrief_2">Ya</label>
                    <label class="margin-left-medium"><input type="radio" value="0" name="dbrief_2">Tidak</label>
                </div>
                <br>
                <br>

                <div class="flex center-horizontal">
                    <input type="submit" value="Lanjut" class="btn btn-outline-dark one-third">
                </div>
            </div>
        </form>
    </div>
</div>
<div style="height: 40px;"></div>
</body>
</html>