<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Gathering</title>
    <link rel="stylesheet" href="static/css/app.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
          integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<style>
    @media screen and (min-width: 556px) {
        .ul-list {
            margin-left: 26vw !important;
            margin-right: 25vw !important;
        }
    }

    ul {
        list-style-type: none;
        padding-left: 0px;
    }

    li {
        display: inline-block;
    }

    input[type="checkbox"][id^="cb"] {
        display: none;
    }

    label {
        border: 1px solid #fff;
        /*padding: 10px;*/
        display: block;
        position: relative;
        /*margin: 10px;*/
        cursor: pointer;
    }

    label:before {
        background-color: white;
        color: white;
        content: " ";
        display: block;
        border-radius: 50%;
        border: 1px solid grey;
        position: absolute;
        z-index: 1;
        top: -5px;
        left: -5px;
        width: 25px;
        height: 25px;
        text-align: center;
        line-height: 28px;
        transition-duration: 0.4s;
        transform: scale(0);
    }

    label img {
        height: 80px;
        width: 80px;
        transition-duration: 0.2s;
        transform-origin: 50% 50%;
    }

    :checked + label {
        border-color: #ddd;
    }

    :checked + label:before {
        content: "✓";
        background-color: grey;
        transform: scale(1);
    }

    :checked + label img {
        transform: scale(0.9);
        box-shadow: 0 0 5px #333;
        z-index: -1;
    }

    .ul-list {
        margin-left: 0vw;
        margin-right: 0vw;
    }
</style>


<body class="bg">
<div style="height: 70px;"></div>
<div class="container">
    <div class="box-home padding-medium">
<!--        <div class="flex center-horizontal text-size-very-small" style="text-align: justify">-->
            <div class="text-center">
                <h1></h1>
            </div>
            <div class="text-center">
                <p>Pilih semua gambar yang terdapat objek <span id="cari">gunung</span></p>
            </div>
        <form method="post" id="checkboxes" action="/forms" >
            <input type="hidden" name="abis" value="apalah"/>
            <div class="ul-list">
                <ul>
                    <li><input type="checkbox" name="selectedImage[]" id="cb1" value="1" />
                        <label for="cb1"><img id="img1" src= "static/1.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb2" value="2" />
                        <label for="cb2"><img id="img2" src= "static/2.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb3" value="3" />
                        <label for="cb3"><img id="img3" src="static/3.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb4" value="4" />
                        <label for="cb4"><img id="img4" src="static/4.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb5" value="5" />
                        <label for="cb5"><img id="img5" src="static/5.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb6" value="6" />
                        <label for="cb6"><img id="img6" src="static/6.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb7" value="7" />
                        <label for="cb7"><img id="img7" src="static/7.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb8" value="8" />
                        <label for="cb8"><img id="img8" src="static/8.jpg" /></label>
                    </li>
                    <li><input type="checkbox" name="selectedImage[]" id="cb9" value="9" />
                        <label for="cb9"><img id="img9" src="static/9.jpg" /></label>

                    </li>
                </ul>
            </div>
            <div class="flex center-horizontal margin-bot-medium">
                <input type="submit" value="Lanjut" class="btn btn-outline-dark one-third text-size-very-small">
            </div>
            <input type="hidden" name="state" value=<?php echo $state; ?>>
        </form>
    </div>
</div>
<div style="height: 40px;"></div>
</body>
</body>

<script type="text/javascript">
    let element = document.getElementById("checkboxes");

    state = 0;

    let correct1 = [true, false, false, true, false, true, false, true, false];
    let correct2 = [true, false, true, true, false, false, true, false, true];
    let correct3 = [true, true, false, true, true, false, true, false, false];

    element.addEventListener('submit', function (e) {
        e.preventDefault();
        let falseAnswer = 0;
        if (state === 0) {
            falseAnswer = validate(correct1);
        } else if (state === 1) {
            falseAnswer = validate(correct2);
        } else if (state === 2) {
            falseAnswer = validate(correct3);
        }

        if (falseAnswer > 0) {
            alert("Jawaban Anda salah");
        } else {
            if (state === 2) {
                element.submit();
            } else {
                state = state + 1;
                for (let i = 1; i <= 9; i = i + 1) document.getElementById("cb" + i).checked = false;
                changePhoto(state);
            }
        }

    }, false);

    function changePhoto(state) {
        let baseUrl = "";
        let name = "";
        if (state === 1) {
            baseUrl = "static/distract/jembatan";
            name = "Jembatan";
        } else {
            baseUrl = "static/distract/sungai";
            name = "Sungai"
        }
        document.getElementById("cari").innerHTML = name;

        for (let i = 1; i <= 9; i = i + 1) {
            let id = "img" + i;
            document.getElementById(id).src = baseUrl + i + ".jpg";
        }
    }

    function validate(correct) {
        var cb1 = document.getElementById("cb1").checked === correct[0] ? 0 : 1;
        var cb2 = document.getElementById("cb2").checked === correct[1] ? 0 : 1;
        var cb3 = document.getElementById("cb3").checked === correct[2] ? 0 : 1;
        var cb4 = document.getElementById("cb4").checked === correct[3] ? 0 : 1;
        var cb5 = document.getElementById("cb5").checked === correct[4] ? 0 : 1;
        var cb6 = document.getElementById("cb6").checked === correct[5] ? 0 : 1;
        var cb7 = document.getElementById("cb7").checked === correct[6] ? 0 : 1;
        var cb8 = document.getElementById("cb8").checked === correct[7] ? 0 : 1;
        var cb9 = document.getElementById("cb9").checked === correct[8] ? 0 : 1;

        return cb1 + cb2 + cb3 + cb4 + cb5 + cb6 + cb7 + cb8 + cb9;
    }

</script>
</html>

