<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Gathering</title>
    <link rel="stylesheet" href="static/css/app.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>

<body class="bg">
<div style="height: 70px;"></div>
<div class="container">
    <div class="box-home padding-medium">
        <div class="flex center-horizontal text-size-very-small" style="text-align: justify">
            <div class="margin-medium">
                <p>
                    Perkenalkan saya Ladayna Nurul Arasy mahasiswa semester 8, Fakultas Psikologi Universitas Indonesia. Saat ini saya sedang melakukan survei dalam rangka pengambilan data untuk memenuhi Tugas Akhir Skripsi. Survei ini dilakukan untuk melihat pengaruh media terhadap dukungan politik individu. Jika Anda bersedia untuk berpartisipasi dalam survei ini, Anda akan diminta untuk melengkapi data diri, menentukan dukungan politik, membaca artikel, dan mengisi kuesioner singkat. Waktu yang dibutuhkan untuk mengisi survei ini kira-kira berkisar antara 5-10 menit. Semua informasi yang Anda berikan dalam survei ini akan disimpan secara rahasia. Hanya peneliti yang memiliki akses terhadap data yang Anda berikan dan hanya akan digunakan untuk kepentingan penelitian ini.
                </p>
                <p>
                    Partisipasi Anda sepenuhnya sukarela dan tanpa paksaan. Anda berhak untuk memperoleh informasi mengenai hasil dari penelitian yang saya lakukan. Di sisi lain, Anda juga berhak untuk berhenti sebagai partisipan dalam penelitian ini kapanpun tanpa mendapatkan konsekuensi apapun. Apabila terdapat beberapa pertanyaan terkait penelitian ini dan ingin mengetahui hasil dari penelitian ini, Anda dapat menghubungi peneliti melalui email atau nomor telepon peneliti (ladayna.nurul@ui.ac.id / 082112609646).
                <p>
                    Apabila Anda bersedia menjadi partisipan dalam penelitian ini, silahkan klik kotak yang berisikan tulisan bersedia dibawah ini.</p>
            </div>
        </div>
        <form class="flex center-horizontal margin-bot-medium" action="/forms">
            <input type="submit" value="Bersedia" class="btn btn-outline-dark one-third text-size-very-small">
        </form>
        <div class="flex text-size-very-small margin-large" style="text-align: left">
            <p>Atas kesediaan Anda, saya ucapkan terima kasih.<br>
                Salam Peneliti,<br>
                Ladayna Nurul Arasy
            </p>
        </div>
    </div>
</div>
<div style="height: 40px;"></div>
</body>
</html>