<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Gathering</title>
    <link rel="stylesheet" href="static/css/app.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>

<body class="bg">

<?php
if ($position == 0) {
    $first = "Jokowi";
    $second = "Prabowo";
    $first_photo = "static/jokowi.jpg";
    $second_photo = "static/prabowo.jpg";
} else {
    $first = "Prabowo";
    $second = "Jokowi";
    $first_photo = "static/prabowo.jpg";
    $second_photo = "static/jokowi.jpg";
}
?>

<div style="height: 70px;"></div>
<div class="container">
    <div class="box-home padding-medium">
        <div class="margin-large" style="text-align: justify">
            Anda diminta untuk menentukan posisi Anda, apakah mendukung Jokowi atau mendukung Prabowo dari rentang skala 0-10 dibawah ini. Tunjukkan posisi Anda dengan cara menggeser lingkaran biru di bawah ini.
        </div>
        <form method="post" class="margin-bot-medium" action="/forms">
            <div class="margin-left-very-large margin-right-very-large margin-bot-medium">
                <div class="flex center-horizontal">
                    <input name="tendency" type="range" class="custom-range" min="0" max="20" id="customRange3" oninput="changeDetail(customRange3.value)">
                </div>
                <div class="center-horizontal flex">
                    <div class="flex space-beetween full-width margin-top-small">
                        <div class="flex text-size-small" style="width: 5%">10</div>
                        <div class="flex center-horizontal text-size-small" style="width: 5%">0</div>
                        <div class="flex align-right text-size-small" style="width: 5%">10</div>
                    </div>
                </div>
            </div>
            <div class="flex space-beetween margin-top-small">
                <div>
                    <div class="flex center-horizontal">
                        <img src=<?php echo $first_photo;?> class="candidate-img"/>
                    </div>
                    <div class="margin-top-small text-size-very-small flex center-horizontal"><strong id="first"><?php echo $first;?></strong></div>
                </div>
                <div class="flex center-vertical">
                    <div>
                        <div class="flex center-horizontal" style="font-size: 50px;" id="value">0</div>
                        <div class="flex center-horizontal" id="name">Netral</div>
                    </div>
                </div>
                <div>
                    <div class="flex center-horizontal">
                        <img src=<?php echo $second_photo;?> class="candidate-img"/>
                    </div>
                    <div class="margin-top-small text-size-very-small flex center-horizontal"><strong id="second"><?php echo $second;?></strong></div>
                </div>
            </div>
            <input type="hidden" name="state" value=<?php echo $state;?>>
            <input type="hidden" id="firstPicked" name="firstPicked" value="Netral">
            <div class="flex center-horizontal margin-top-medium">
                <input type="submit" value="Next" class="btn btn-outline-dark quarter margin-top-medium">
            </div>
        </form>
    </div>
</div>
<div style="height: 40px;"></div>
</body>

<script>
    function changeDetail(val) {
        let number = document.getElementById('value');
        let name = document.getElementById('name');
        let comment = 'Netral';
        let x = 10;
        let print = 0;
        if (val < 10) {
            comment = document.getElementById('first').innerHTML;
            x = val;
            print = 10 - x;
        } else if (val > 10) {
            comment = document.getElementById('second').innerHTML;
            x = 10 - (val - 10);
            print = 10 - x;
        }

        name.innerHTML = comment;
        document.getElementById("firstPicked").value = comment;
        number.innerHTML = print;

    }
</script>
</html>