<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Data Gathering</title>
    <link rel="stylesheet" href="static/css/app.css">
    <link rel="stylesheet" href="static/css/bulb.css">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>

<body class="bg">
<div style="height: 70px;"></div>
<div class="container">
    <div class="box-home padding-medium">
        <form method="post" class="center-horizontal margin-bot-medium" action='/forms'>
            <div class="flex center-horizontal text-size-very-small margin-bot-very-large" style="text-align: justify"><strong>
                    Berikut ini akan disajikan beberapa pernyataan. Baca dan pahami baik-baik setiap pernyataan. Anda diminta untuk menjawab sesuai dengan instruksi yang diberikan pada setiap bagian.
                </strong></div>

            <div class="flex center-horizontal text-size-very-small margin-top-very-large" style="text-align: justify">
                Anda diminta untuk menilai perasaan Anda terhadap Jokowi menggunakan termometer yang terentang dari  0°-100°. Tunjukkan penilaian Anda dengan cara menggeser lingkaran biru dibawah ini.
            </div>
            <br>
            <div> 0°   = Anda merasa Jokowi sangat tidak baik dan tidak hangat.</div>
            <div>100°= Anda merasa Jokowi sangat baik dan hangat.</div>

            <div class="flex row margin-top-large">
                <div class="donation-meter quarter">
                    <span class="glass">
                            <strong id="total" class="total" style="bottom: 50%">50°</strong>
                            <span id="amount" class="amount" style="height: 50%"></span>
                        </span>
                    <div class="bulb">
                        <span class="red-circle"></span>
                        <span class="filler">
                                <span></span>
                            </span>
                    </div>
                </div>
                <div class="half flex center-vertical">
                    <div class="full-width">
                        <input name="thermometer" type="range" class="custom-range" min="0" max="100" id="customRange3" oninput="changeDetail(customRange3.value)">
                        <div class="full-width flex space-beetween">
                            <div class="text-size-small">0°</div>
                            <div class="text-size-small">50°</div>
                            <div class="text-size-small">100°</div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="flex center-horizontal text-size-very-small" style="text-align: justify">
                <div class="margin-large">
                    <strong>
                        Berikut ini terdapat beberapa pernyataan. Anda diminta untuk menilai seberapa sesuai karakteristik tersebut dengan Jokowi menggunakan 1-6 poin skala likert.                    </strong>
                        <br>
                    <br>
                    1 =  Sangat tidak sesuai
                    <br>
                    2 = Tidak sesuai
                    <br>
                    3 = Agak tidak sesuai
                    <br>
                    4 = Agak sesuai
                    <br>
                    5 = Sesuai
                    <br>
                    6 = Sangat sesuai
                </div>
            </div>
            <input type="hidden" name="state" value=<?php echo $state;?>>
            <div class="text-size-very-small">
                Seorang politikus yang baik, aktif dalam berpolitik
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium colored" >
                            <input type="radio" name="op1" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium colored">
                            <input type="radio" name="op1" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium colored">
                            <input type="radio" name="op1" value="3" required>
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium colored">
                            <input type="radio" name="op1" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium colored">
                            <input type="radio" name="op1" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium colored">
                            <input type="radio" name="op1" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Jujur, menepati janji, pria berintegritas, yakin dengan perkataannya, konsisten
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op2" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op2" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op2" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op2" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op2" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op2" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Pria dengan prinsip yang kuat, bermoral tinggi, idealistis
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op3" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op3" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op3" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op3" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op3" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op3" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Pemerintahan jujur, tidak korupsi
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op4" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op4" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op4" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op4" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op4" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op4" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Dapat diandalkan, pria yang dapat dipercayai dengan tanggung jawab pemerintahan
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op5" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op5" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op5" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op5" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op5" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op5" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Terlalu berhati-hati
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op6" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op6" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op6" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op6" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op6" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op6" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Mewakil rakyat, pria bertanggung jawab, bertujuan baik, pekerja keras
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op7" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op7" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op7" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op7" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op7" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op7" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Baik untuk negara, mengetahui kebutuhan negara
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op8" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op8" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op8" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op8" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op8" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op8" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Seorang figur politik, memiliki pengalaman diplomatis
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op9" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op9" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op9" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op9" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op9" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op9" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Tidak ketergantungan, tidak diperintah siapa-siapa; bos diri sendiri
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op10" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op10" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op10" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op10" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op10" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op10" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Mengerti masalah negara, berwawasan luas
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op11" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op11" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op11" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op11" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op11" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op11" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Menggunakan akal sehat, masuk akal
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op12" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op12" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op12" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op12" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op12" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op12" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Pelindung yang baik, tahu apa yang harus dilakukan
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op13" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op13" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op13" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op13" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op13" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op13" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Orang-orang percaya padanya
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op14" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op14" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op14" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op14" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op14" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op14" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Tahu bagaimana cara mengatasi orang
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op15" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op15" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op15" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op15" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op15" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op15" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Supel
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op16" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op16" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op16" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op16" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op16" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op16" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Demokratis
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op17" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op17" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op17" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op17" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op17" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op17" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Akan mempersatukan Indonesia
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op18" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op18" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op18" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op18" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op18" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op18" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Mapan, kaya, berasal dari keluarga berkecukupan
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op19" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op19" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op19" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op19" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op19" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op19" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Terpandang
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op20" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op20" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op20" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op20" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op20" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op20" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Memiliki kemampuan bicara yang baik
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op21" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op21" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op21" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op21" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op21" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op21" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Penampilan fisiknya di TV menarik
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op22" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op22" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op22" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op22" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op22" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op22" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-size-very-small padding-bot-large">
                Dewasa
            </div>
            <table class="table-responsive">
                <th style="text-align: center"></th>
                <tr>
                    <td>
                        <div class="text-center padding-right-medium" >
                            <input type="radio" name="op23" value="1">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op23" value="2">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op23" required value="3">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op23" value="4">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op23" value="5">
                        </div>
                    </td>
                    <td>
                        <div class="text-center padding-right-medium">
                            <input type="radio" name="op23" value="6">
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">1</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">2</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">3</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">4</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">5</div>
                    </td>
                    <td>
                        <div class="text-size-very-very-small text-center padding-right-medium">6</div>
                    </td>
                </tr>
            </table>

            <div class="text-center padding-bot-large" >
                <input type="submit" value="Lanjut" class="btn btn-outline-dark quarter ">
            </div>
        </form>
    </div>
</div>
<div style="height: 40px;"></div>
</body>

<script>
    function changeDetail(val) {
        let total = document.getElementById("total");
        let amount = document.getElementById("amount");
        total.style.bottom = val + "%";
        amount.style.height = val + "%";
        total.innerHTML = val + "°";
    }
</script>


</html>